### ISSUE TITLE
Devtools classes

### ISSUE THREAD

**Issue by entozoon** [kenwheeler/brogrammer-devtools#2]
This is going to sound dumb, but how did you find out all the devtools classes in order to style them?
.panel.sources .split-view-vertical .split-view-contents ... etc?

**Comment by kenwheeler** [comment]
Not dumb. Check this shit out. Open up dev tools. Make sure it's undocked from the window, so it is its own window. Then use your key command on that window to open dev tools for it. You now have a dev tools inspecting your dev tools, dawg.

**Comment by entozoon** [comment]
HOLY FUCKBALLS.
I can't even..

thank you!
